(define (problem bw_5_30495)
  (:domain prob_blocks)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on-table b1) (on b2 b1) (on b3 b2) (on-table b4) (on-table b5) (clear b3) (clear b4) (clear b5)
  (pickup b1) (pickup b2) (pickup b3) (pickup b4) (pickup b5)
  (pickupfromtable b1) (pickupfromtable b2) (pickupfromtable b3) (pickupfromtable b4) (pickupfromtable b5)
  (putonblock b1) (putonblock b2) (putonblock b3) (putonblock b4) (putonblock b5)
  (picktower b1) (picktower b2) (picktower b3) (picktower b4) (picktower b5)
  (puttoweronblock b1) (puttoweronblock b2) (puttoweronblock b3) (puttoweronblock b4) (puttoweronblock b5)
  (putdown)))
  (:goal (and (emptyhand) (on b1 b4) (on b2 b5) (on-table b3) (on b4 b2) (on b5 b3) (clear b1)))
)
