(define (problem bw_10_5555)
  (:domain prob_blocks)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
  (:init (emptyhand) (on b1 b8) (on-table b2) (on b3 b4) (on b4 b9) (on b5 b1) (on b6 b7) (on b7 b5) (on-table b8) (on b9 b6) (on b10 b3) (clear b2) (clear b10)
  (pickup b1) (pickup b2) (pickup b3) (pickup b4) (pickup b5) (pickup b6) (pickup b7) (pickup b8) (pickup b9) (pickup b10)
  (pickupfromtable b1) (pickupfromtable b2) (pickupfromtable b3) (pickupfromtable b4) (pickupfromtable b5) (pickupfromtable b6) (pickupfromtable b7) (pickupfromtable b8) (pickupfromtable b9) (pickupfromtable b10)
  (putonblock b1) (putonblock b2) (putonblock b3) (putonblock b4) (putonblock b5) (putonblock b6) (putonblock b7) (putonblock b8) (putonblock b9) (putonblock b10)
  (picktower b1) (picktower b2) (picktower b3) (picktower b4) (picktower b5) (picktower b6) (picktower b7) (picktower b8) (picktower b9) (picktower b10)
  (puttoweronblock b1) (puttoweronblock b2) (puttoweronblock b3) (puttoweronblock b4) (puttoweronblock b5) (puttoweronblock b6) (puttoweronblock b7) (puttoweronblock b8) (puttoweronblock b9) (puttoweronblock b10)
  (putdown))
  (:goal (and (emptyhand) (on b1 b4) (on-table b2) (on-table b3) (on b4 b8) (on b5 b2) (on-table b6) (on-table b7) (on b8 b7) (on b9 b1) (on b10 b5) (clear b3) (clear b6) (clear b9) (clear b10)))
)
