(define (problem ex_bw_5_1318)
  (:domain exploding-blocksworld)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on-table b1) (on b2 b5) (on-table b3) (on-table b4) (on b5 b4) (clear b1) (clear b2) (clear b3) (no-detonated b1) (no-destroyed b1) (no-detonated b2) (no-destroyed b2) (no-detonated b3) (no-destroyed b3) (no-detonated b4) (no-destroyed b4) (no-detonated b5) (no-destroyed b5) (no-destroyed-table) 
  (pickup b1) (pickup b2) (pickup b3) (pickup b4) (pickup b5) 
  (pickupfromtable b1) (pickupfromtable b2) (pickupfromtable b3) (pickupfromtable b4) (pickupfromtable b5) 
  (putonblock b1) (putonblock b2) (putonblock b3) (putonblock b4) (putonblock b5) 
  (putdown))
  (:goal (and (on b3 b4) (on b5 b1)))
)
