(define (problem ex_bw_10_13881)
  (:domain exploding-blocksworld)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 - block)
  (:init (emptyhand) (on-table b1) (on b2 b3) (on b3 b1) (on-table b4) (on b5 b6) (on b6 b8) (on b7 b4) (on b8 b2) (on-table b9) (on b10 b7) (clear b5) (clear b9) (clear b10) (no-detonated b1) (no-destroyed b1) (no-detonated b2) (no-destroyed b2) (no-detonated b3) (no-destroyed b3) (no-detonated b4) (no-destroyed b4) (no-detonated b5) (no-destroyed b5) (no-detonated b6) (no-destroyed b6) (no-detonated b7) (no-destroyed b7) (no-detonated b8) (no-destroyed b8) (no-detonated b9) (no-destroyed b9) (no-detonated b10) (no-destroyed b10) (no-destroyed-table) 
  (pickup b1) (pickup b2) (pickup b3) (pickup b4) (pickup b5) (pickup b6) (pickup b7) (pickup b8) (pickup b9) (pickup b10) 
  (pickupfromtable b1) (pickupfromtable b2) (pickupfromtable b3) (pickupfromtable b4) (pickupfromtable b5) (pickupfromtable b6) (pickupfromtable b7) (pickupfromtable b8) (pickupfromtable b9) (pickupfromtable b10) 
  (putonblock b1) (putonblock b2) (putonblock b3) (putonblock b4) (putonblock b5) (putonblock b6) (putonblock b7) (putonblock b8) (putonblock b9) (putonblock b10) 
  (putdown))
  (:goal (and (on b1 b8) (on b2 b10) (on b7 b5) (on b9 b7) (on-table b10)))
)
