(define (problem zeno_8_2_2_3674)
  (:domain zenotravel)
  (:objects c0 - city c1 - city c2 - city c3 - city c4 - city c5 - city c6 - city c7 - city p0 - person p1 - person a0 - aircraft a1 - aircraft f0 - flevel f1 - flevel f2 - flevel f3 - flevel f4 - flevel )
  (:init (person0 p0) (person1 p1) (completeboarding p0) (startdebarking p0) (completedebarking p0) (completeboarding p1) (startdebarking p1) (completedebarking p1) (completeflying a0) (completezooming a0) (startrefueling a0) (completerefueling a0) (startflying a0 c0) (startzooming a0 c0) (startflying a0 c1) (startzooming a0 c1) (startflying a0 c2) (startzooming a0 c2) (startflying a0 c3) (startzooming a0 c3) (startflying a0 c4) (startzooming a0 c4) (startflying a0 c5) (startzooming a0 c5) (startflying a0 c6) (startzooming a0 c6) (startflying a0 c7) (startzooming a0 c7) (startboarding p0 a0) (startboarding p1 a0) (completeflying a1) (completezooming a1) (startrefueling a1) (completerefueling a1) (startflying a1 c0) (startzooming a1 c0) (startflying a1 c1) (startzooming a1 c1) (startflying a1 c2) (startzooming a1 c2) (startflying a1 c3) (startzooming a1 c3) (startflying a1 c4) (startzooming a1 c4) (startflying a1 c5) (startzooming a1 c5) (startflying a1 c6) (startzooming a1 c6) (startflying a1 c7) (startzooming a1 c7) (startboarding p0 a1) (startboarding p1 a1) (next f0 f1) (next f1 f2) (next f2 f3) (next f3 f4)
         (at-person p0 c2) (not-boarding p0) (not-debarking p0)
         (at-person p1 c6) (not-boarding p1) (not-debarking p1)
         (at-aircraft a0 c5) (fuel-level a0 f3) (not-refueling a0)
         (at-aircraft a1 c7) (fuel-level a1 f2) (not-refueling a1)
  )
  (:goal (and (at-person p0 c3) (at-person p1 c1)))
)
